language: csharp
solution: dotnet-open-source.sln
mono: none
dotnet: 3.1.200
stages:
 - test
 - publish
jobs:
 include:
  - stage: test
    name: test solution
    script: ./run-tests.sh
  - stage: publish
    name: publish nuget package
    if: tag IS present
    script: ./publish-nuget.sh "$NUGET_SOURCE" "$NUGET_KEY" "$TRAVIS_TAG"
